project_id = "bgznszxombwvwhufowpm"

[functions.generate-seo]
verify_jwt = false

[functions.send-certificate-notification]
verify_jwt = false

[functions.send-teacher-application-email]
verify_jwt = false

[functions.generate-course-image-prompts]
verify_jwt = false

[functions.generate-course-image]
verify_jwt = false
